%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BGGsticky';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('BGGsticky.log');
M_.exo_names = 'e_A';
M_.exo_names_tex = 'e\_A';
M_.exo_names_long = 'e_A';
M_.exo_names = char(M_.exo_names, 'epsilonM');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilonM');
M_.exo_names_long = char(M_.exo_names_long, 'epsilonM');
M_.exo_names = char(M_.exo_names, 'e_G');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_G');
M_.exo_names_long = char(M_.exo_names_long, 'e_G');
M_.exo_names = char(M_.exo_names, 'e_xi1');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_xi1');
M_.exo_names_long = char(M_.exo_names_long, 'e_xi1');
M_.exo_names = char(M_.exo_names, 'e_xi2');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_xi2');
M_.exo_names_long = char(M_.exo_names_long, 'e_xi2');
M_.exo_names = char(M_.exo_names, 'e_xi3');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_xi3');
M_.exo_names_long = char(M_.exo_names_long, 'e_xi3');
M_.exo_names = char(M_.exo_names, 'e_xi4');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_xi4');
M_.exo_names_long = char(M_.exo_names_long, 'e_xi4');
M_.exo_names = char(M_.exo_names, 'e_xi5');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_xi5');
M_.exo_names_long = char(M_.exo_names_long, 'e_xi5');
M_.exo_names = char(M_.exo_names, 'e_xi6');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_xi6');
M_.exo_names_long = char(M_.exo_names_long, 'e_xi6');
M_.exo_names = char(M_.exo_names, 'e_xi7');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_xi7');
M_.exo_names_long = char(M_.exo_names_long, 'e_xi7');
M_.exo_names = char(M_.exo_names, 'e_xi8');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_xi8');
M_.exo_names_long = char(M_.exo_names_long, 'e_xi8');
M_.exo_names = char(M_.exo_names, 'e_RS');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_RS');
M_.exo_names_long = char(M_.exo_names_long, 'e_RS');
M_.endo_names = 'C';
M_.endo_names_tex = 'C';
M_.endo_names_long = 'C';
M_.endo_names = char(M_.endo_names, 'Uc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Uc');
M_.endo_names_long = char(M_.endo_names_long, 'Uc');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'Lab');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lab');
M_.endo_names_long = char(M_.endo_names_long, 'Lab');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'W');
M_.endo_names_tex = char(M_.endo_names_tex, 'W');
M_.endo_names_long = char(M_.endo_names_long, 'W');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'Z');
M_.endo_names = char(M_.endo_names, 'A');
M_.endo_names_tex = char(M_.endo_names_tex, 'A');
M_.endo_names_long = char(M_.endo_names_long, 'A');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'Rl');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rl');
M_.endo_names_long = char(M_.endo_names_long, 'Rl');
M_.endo_names = char(M_.endo_names, 'Ne');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ne');
M_.endo_names_long = char(M_.endo_names_long, 'Ne');
M_.endo_names = char(M_.endo_names, 'phie');
M_.endo_names_tex = char(M_.endo_names_tex, 'phie');
M_.endo_names_long = char(M_.endo_names_long, 'phie');
M_.endo_names = char(M_.endo_names, 'Le');
M_.endo_names_tex = char(M_.endo_names_tex, 'Le');
M_.endo_names_long = char(M_.endo_names_long, 'Le');
M_.endo_names = char(M_.endo_names, 'Ce');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ce');
M_.endo_names_long = char(M_.endo_names_long, 'Ce');
M_.endo_names = char(M_.endo_names, 'rho');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho');
M_.endo_names_long = char(M_.endo_names_long, 'rho');
M_.endo_names = char(M_.endo_names, 'rhoRex');
M_.endo_names_tex = char(M_.endo_names_tex, 'rhoRex');
M_.endo_names_long = char(M_.endo_names_long, 'rhoRex');
M_.endo_names = char(M_.endo_names, 'omega');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega');
M_.endo_names_long = char(M_.endo_names_long, 'omega');
M_.endo_names = char(M_.endo_names, 'bankrupt');
M_.endo_names_tex = char(M_.endo_names_tex, 'bankrupt');
M_.endo_names_long = char(M_.endo_names_long, 'bankrupt');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'psi');
M_.endo_names_tex = char(M_.endo_names_tex, 'psi');
M_.endo_names_long = char(M_.endo_names_long, 'psi');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'T');
M_.endo_names_tex = char(M_.endo_names_tex, 'T');
M_.endo_names_long = char(M_.endo_names_long, 'T');
M_.endo_names = char(M_.endo_names, 'spread');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread');
M_.endo_names_long = char(M_.endo_names_long, 'spread');
M_.endo_names = char(M_.endo_names, 'sigma_pref');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma\_pref');
M_.endo_names_long = char(M_.endo_names_long, 'sigma_pref');
M_.endo_names = char(M_.endo_names, 'zeta');
M_.endo_names_tex = char(M_.endo_names_tex, 'zeta');
M_.endo_names_long = char(M_.endo_names_long, 'zeta');
M_.endo_names = char(M_.endo_names, 'PIS');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIS');
M_.endo_names_long = char(M_.endo_names_long, 'PIS');
M_.endo_names = char(M_.endo_names, 'PIP');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIP');
M_.endo_names_long = char(M_.endo_names_long, 'PIP');
M_.endo_names = char(M_.endo_names, 'Rn');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rn');
M_.endo_names_long = char(M_.endo_names_long, 'Rn');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'H');
M_.endo_names_tex = char(M_.endo_names_tex, 'H');
M_.endo_names_long = char(M_.endo_names_long, 'H');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'Ym');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ym');
M_.endo_names_long = char(M_.endo_names_long, 'Ym');
M_.endo_names = char(M_.endo_names, 'Pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pm');
M_.endo_names_long = char(M_.endo_names_long, 'Pm');
M_.endo_names = char(M_.endo_names, 'sigmae');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigmae');
M_.endo_names_long = char(M_.endo_names_long, 'sigmae');
M_.endo_names = char(M_.endo_names, 'sigma_omega');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma\_omega');
M_.endo_names_long = char(M_.endo_names_long, 'sigma_omega');
M_.endo_names = char(M_.endo_names, 'mon');
M_.endo_names_tex = char(M_.endo_names_tex, 'mon');
M_.endo_names_long = char(M_.endo_names_long, 'mon');
M_.endo_names = char(M_.endo_names, 'sigma_omega_ss');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma\_omega\_ss');
M_.endo_names_long = char(M_.endo_names_long, 'sigma_omega_ss');
M_.endo_names = char(M_.endo_names, 'Sg');
M_.endo_names_tex = char(M_.endo_names_tex, 'Sg');
M_.endo_names_long = char(M_.endo_names_long, 'Sg');
M_.endo_names = char(M_.endo_names, 'xi0');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi0');
M_.endo_names_long = char(M_.endo_names_long, 'xi0');
M_.endo_names = char(M_.endo_names, 'xi1');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi1');
M_.endo_names_long = char(M_.endo_names_long, 'xi1');
M_.endo_names = char(M_.endo_names, 'xi2');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi2');
M_.endo_names_long = char(M_.endo_names_long, 'xi2');
M_.endo_names = char(M_.endo_names, 'xi3');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi3');
M_.endo_names_long = char(M_.endo_names_long, 'xi3');
M_.endo_names = char(M_.endo_names, 'xi4');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi4');
M_.endo_names_long = char(M_.endo_names_long, 'xi4');
M_.endo_names = char(M_.endo_names, 'xi5');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi5');
M_.endo_names_long = char(M_.endo_names_long, 'xi5');
M_.endo_names = char(M_.endo_names, 'xi6');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi6');
M_.endo_names_long = char(M_.endo_names_long, 'xi6');
M_.endo_names = char(M_.endo_names, 'xi7');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi7');
M_.endo_names_long = char(M_.endo_names_long, 'xi7');
M_.endo_names = char(M_.endo_names, 'xi8');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi8');
M_.endo_names_long = char(M_.endo_names_long, 'xi8');
M_.endo_names = char(M_.endo_names, 'log_xi0');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_xi0');
M_.endo_names_long = char(M_.endo_names_long, 'log_xi0');
M_.endo_names = char(M_.endo_names, 'log_xi1');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_xi1');
M_.endo_names_long = char(M_.endo_names_long, 'log_xi1');
M_.endo_names = char(M_.endo_names, 'log_xi2');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_xi2');
M_.endo_names_long = char(M_.endo_names_long, 'log_xi2');
M_.endo_names = char(M_.endo_names, 'log_xi3');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_xi3');
M_.endo_names_long = char(M_.endo_names_long, 'log_xi3');
M_.endo_names = char(M_.endo_names, 'log_xi4');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_xi4');
M_.endo_names_long = char(M_.endo_names_long, 'log_xi4');
M_.endo_names = char(M_.endo_names, 'log_xi5');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_xi5');
M_.endo_names_long = char(M_.endo_names_long, 'log_xi5');
M_.endo_names = char(M_.endo_names, 'log_xi6');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_xi6');
M_.endo_names_long = char(M_.endo_names_long, 'log_xi6');
M_.endo_names = char(M_.endo_names, 'log_xi7');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_xi7');
M_.endo_names_long = char(M_.endo_names_long, 'log_xi7');
M_.endo_names = char(M_.endo_names, 'log_xi8');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_xi8');
M_.endo_names_long = char(M_.endo_names_long, 'log_xi8');
M_.endo_names = char(M_.endo_names, 'Cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cf');
M_.endo_names_long = char(M_.endo_names_long, 'Cf');
M_.endo_names = char(M_.endo_names, 'Ucf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ucf');
M_.endo_names_long = char(M_.endo_names_long, 'Ucf');
M_.endo_names = char(M_.endo_names, 'Lambdaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambdaf');
M_.endo_names_long = char(M_.endo_names_long, 'Lambdaf');
M_.endo_names = char(M_.endo_names, 'Labf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Labf');
M_.endo_names_long = char(M_.endo_names_long, 'Labf');
M_.endo_names = char(M_.endo_names, 'Rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rf');
M_.endo_names_long = char(M_.endo_names_long, 'Rf');
M_.endo_names = char(M_.endo_names, 'Ymf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ymf');
M_.endo_names_long = char(M_.endo_names_long, 'Ymf');
M_.endo_names = char(M_.endo_names, 'Kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kf');
M_.endo_names_long = char(M_.endo_names_long, 'Kf');
M_.endo_names = char(M_.endo_names, 'Wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Wf');
M_.endo_names_long = char(M_.endo_names_long, 'Wf');
M_.endo_names = char(M_.endo_names, 'Rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rkf');
M_.endo_names_long = char(M_.endo_names_long, 'Rkf');
M_.endo_names = char(M_.endo_names, 'If');
M_.endo_names_tex = char(M_.endo_names_tex, 'If');
M_.endo_names_long = char(M_.endo_names_long, 'If');
M_.endo_names = char(M_.endo_names, 'Qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qf');
M_.endo_names_long = char(M_.endo_names_long, 'Qf');
M_.endo_names = char(M_.endo_names, 'Gf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gf');
M_.endo_names_long = char(M_.endo_names_long, 'Gf');
M_.endo_names = char(M_.endo_names, 'Tf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tf');
M_.endo_names_long = char(M_.endo_names_long, 'Tf');
M_.endo_names = char(M_.endo_names, 'OUTGAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'OUTGAP');
M_.endo_names_long = char(M_.endo_names_long, 'OUTGAP');
M_.endo_names = char(M_.endo_names, 'Pmf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pmf');
M_.endo_names_long = char(M_.endo_names_long, 'Pmf');
M_.endo_names = char(M_.endo_names, 'Zf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zf');
M_.endo_names_long = char(M_.endo_names_long, 'Zf');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'fnG');
M_.endo_names_tex = char(M_.endo_names_tex, 'fnG');
M_.endo_names_long = char(M_.endo_names_long, 'fnG');
M_.endo_names = char(M_.endo_names, 'fnGam');
M_.endo_names_tex = char(M_.endo_names_tex, 'fnGam');
M_.endo_names_long = char(M_.endo_names_long, 'fnGam');
M_.endo_names = char(M_.endo_names, 'DGam');
M_.endo_names_tex = char(M_.endo_names_tex, 'DGam');
M_.endo_names_long = char(M_.endo_names_long, 'DGam');
M_.endo_names = char(M_.endo_names, 'DG');
M_.endo_names_tex = char(M_.endo_names_tex, 'DG');
M_.endo_names_long = char(M_.endo_names_long, 'DG');
M_.endo_names = char(M_.endo_names, 'YY');
M_.endo_names_tex = char(M_.endo_names_tex, 'YY');
M_.endo_names_long = char(M_.endo_names_long, 'YY');
M_.endo_names = char(M_.endo_names, 'CC');
M_.endo_names_tex = char(M_.endo_names_tex, 'CC');
M_.endo_names_long = char(M_.endo_names_long, 'CC');
M_.endo_names = char(M_.endo_names, 'II');
M_.endo_names_tex = char(M_.endo_names_tex, 'II');
M_.endo_names_long = char(M_.endo_names_long, 'II');
M_.endo_names = char(M_.endo_names, 'WW');
M_.endo_names_tex = char(M_.endo_names_tex, 'WW');
M_.endo_names_long = char(M_.endo_names_long, 'WW');
M_.endo_names = char(M_.endo_names, 'RR');
M_.endo_names_tex = char(M_.endo_names_tex, 'RR');
M_.endo_names_long = char(M_.endo_names_long, 'RR');
M_.endo_names = char(M_.endo_names, 'QQ');
M_.endo_names_tex = char(M_.endo_names_tex, 'QQ');
M_.endo_names_long = char(M_.endo_names_long, 'QQ');
M_.endo_names = char(M_.endo_names, 'RnRn');
M_.endo_names_tex = char(M_.endo_names_tex, 'RnRn');
M_.endo_names_long = char(M_.endo_names_long, 'RnRn');
M_.endo_names = char(M_.endo_names, 'PIPPIP');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIPPIP');
M_.endo_names_long = char(M_.endo_names_long, 'PIPPIP');
M_.endo_names = char(M_.endo_names, 'OUTGAPOUTGAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'OUTGAPOUTGAP');
M_.endo_names_long = char(M_.endo_names_long, 'OUTGAPOUTGAP');
M_.endo_names = char(M_.endo_names, 'RkRk');
M_.endo_names_tex = char(M_.endo_names_tex, 'RkRk');
M_.endo_names_long = char(M_.endo_names_long, 'RkRk');
M_.endo_names = char(M_.endo_names, 'NeNe');
M_.endo_names_tex = char(M_.endo_names_tex, 'NeNe');
M_.endo_names_long = char(M_.endo_names_long, 'NeNe');
M_.endo_names = char(M_.endo_names, 'spreadspread');
M_.endo_names_tex = char(M_.endo_names_tex, 'spreadspread');
M_.endo_names_long = char(M_.endo_names_long, 'spreadspread');
M_.endo_names = char(M_.endo_names, 'KK');
M_.endo_names_tex = char(M_.endo_names_tex, 'KK');
M_.endo_names_long = char(M_.endo_names_long, 'KK');
M_.endo_names = char(M_.endo_names, 'rhorho');
M_.endo_names_tex = char(M_.endo_names_tex, 'rhorho');
M_.endo_names_long = char(M_.endo_names_long, 'rhorho');
M_.endo_names = char(M_.endo_names, 'LabLab');
M_.endo_names_tex = char(M_.endo_names_tex, 'LabLab');
M_.endo_names_long = char(M_.endo_names_long, 'LabLab');
M_.endo_names = char(M_.endo_names, 'phiephie');
M_.endo_names_tex = char(M_.endo_names_tex, 'phiephie');
M_.endo_names_long = char(M_.endo_names_long, 'phiephie');
M_.endo_names = char(M_.endo_names, 'psipsi');
M_.endo_names_tex = char(M_.endo_names_tex, 'psipsi');
M_.endo_names_long = char(M_.endo_names_long, 'psipsi');
M_.endo_names = char(M_.endo_names, 'LeLe');
M_.endo_names_tex = char(M_.endo_names_tex, 'LeLe');
M_.endo_names_long = char(M_.endo_names_long, 'LeLe');
M_.endo_names = char(M_.endo_names, 'YYF');
M_.endo_names_tex = char(M_.endo_names_tex, 'YYF');
M_.endo_names_long = char(M_.endo_names_long, 'YYF');
M_.endo_names = char(M_.endo_names, 'CCF');
M_.endo_names_tex = char(M_.endo_names_tex, 'CCF');
M_.endo_names_long = char(M_.endo_names_long, 'CCF');
M_.endo_names = char(M_.endo_names, 'IIF');
M_.endo_names_tex = char(M_.endo_names_tex, 'IIF');
M_.endo_names_long = char(M_.endo_names_long, 'IIF');
M_.endo_names = char(M_.endo_names, 'WWF');
M_.endo_names_tex = char(M_.endo_names_tex, 'WWF');
M_.endo_names_long = char(M_.endo_names_long, 'WWF');
M_.endo_names = char(M_.endo_names, 'RRF');
M_.endo_names_tex = char(M_.endo_names_tex, 'RRF');
M_.endo_names_long = char(M_.endo_names_long, 'RRF');
M_.endo_names = char(M_.endo_names, 'spreadspreadF');
M_.endo_names_tex = char(M_.endo_names_tex, 'spreadspreadF');
M_.endo_names_long = char(M_.endo_names_long, 'spreadspreadF');
M_.endo_names = char(M_.endo_names, 'LabLabF');
M_.endo_names_tex = char(M_.endo_names_tex, 'LabLabF');
M_.endo_names_long = char(M_.endo_names_long, 'LabLabF');
M_.endo_names = char(M_.endo_names, 'QQF');
M_.endo_names_tex = char(M_.endo_names_tex, 'QQF');
M_.endo_names_long = char(M_.endo_names_long, 'QQF');
M_.endo_names = char(M_.endo_names, 'RkRkF');
M_.endo_names_tex = char(M_.endo_names_tex, 'RkRkF');
M_.endo_names_long = char(M_.endo_names_long, 'RkRkF');
M_.endo_names = char(M_.endo_names, 'KKF');
M_.endo_names_tex = char(M_.endo_names_tex, 'KKF');
M_.endo_names_long = char(M_.endo_names_long, 'KKF');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_45_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_46_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_46\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_46_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_46_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_46\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_46_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_48_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_48\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_48_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_48_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_48\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_48_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_48_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_48\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_48_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_48_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_48\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_48_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_49_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_49\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_49_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_49_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_49\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_49_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_49_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_49\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_49_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_49_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_49\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_49_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_49_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_49\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_49_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_7');
M_.endo_partitions = struct();
M_.param_names = 'alphha';
M_.param_names_tex = 'alphha';
M_.param_names_long = 'alphha';
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'gammma');
M_.param_names_tex = char(M_.param_names_tex, 'gammma');
M_.param_names_long = char(M_.param_names_long, 'gammma');
M_.param_names = char(M_.param_names, 'chil');
M_.param_names_tex = char(M_.param_names_tex, 'chil');
M_.param_names_long = char(M_.param_names_long, 'chil');
M_.param_names = char(M_.param_names, 'epsl');
M_.param_names_tex = char(M_.param_names_tex, 'epsl');
M_.param_names_long = char(M_.param_names_long, 'epsl');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'ksie');
M_.param_names_tex = char(M_.param_names_tex, 'ksie');
M_.param_names_long = char(M_.param_names_long, 'ksie');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'taf');
M_.param_names_tex = char(M_.param_names_tex, 'taf');
M_.param_names_long = char(M_.param_names_long, 'taf');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'phiX');
M_.param_names_tex = char(M_.param_names_tex, 'phiX');
M_.param_names_long = char(M_.param_names_long, 'phiX');
M_.param_names = char(M_.param_names, 'kpY');
M_.param_names_tex = char(M_.param_names_tex, 'kpY');
M_.param_names_long = char(M_.param_names_long, 'kpY');
M_.param_names = char(M_.param_names, 'kpP');
M_.param_names_tex = char(M_.param_names_tex, 'kpP');
M_.param_names_long = char(M_.param_names_long, 'kpP');
M_.param_names = char(M_.param_names, 'rho_r');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_r');
M_.param_names_long = char(M_.param_names_long, 'rho_r');
M_.param_names = char(M_.param_names, 'els');
M_.param_names_tex = char(M_.param_names_tex, 'els');
M_.param_names_long = char(M_.param_names_long, 'els');
M_.param_names = char(M_.param_names, 'gam');
M_.param_names_tex = char(M_.param_names_tex, 'gam');
M_.param_names_long = char(M_.param_names_long, 'gam');
M_.param_names = char(M_.param_names, 'sig');
M_.param_names_tex = char(M_.param_names_tex, 'sig');
M_.param_names_long = char(M_.param_names_long, 'sig');
M_.param_names = char(M_.param_names, 'kap');
M_.param_names_tex = char(M_.param_names_tex, 'kap');
M_.param_names_long = char(M_.param_names_long, 'kap');
M_.param_names = char(M_.param_names, 'zzeta');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta');
M_.param_names_long = char(M_.param_names_long, 'zzeta');
M_.param_names = char(M_.param_names, 'rhosigma');
M_.param_names_tex = char(M_.param_names_tex, 'rhosigma');
M_.param_names_long = char(M_.param_names_long, 'rhosigma');
M_.param_names = char(M_.param_names, 'signal_corr_p');
M_.param_names_tex = char(M_.param_names_tex, 'signal\_corr\_p');
M_.param_names_long = char(M_.param_names_long, 'signal_corr_p');
M_.param_names = char(M_.param_names, 'stdsigma2_p');
M_.param_names_tex = char(M_.param_names_tex, 'stdsigma2\_p');
M_.param_names_long = char(M_.param_names_long, 'stdsigma2_p');
M_.param_names = char(M_.param_names, 'stdsigma1_p');
M_.param_names_tex = char(M_.param_names_tex, 'stdsigma1\_p');
M_.param_names_long = char(M_.param_names_long, 'stdsigma1_p');
M_.param_names = char(M_.param_names, 'stdA');
M_.param_names_tex = char(M_.param_names_tex, 'stdA');
M_.param_names_long = char(M_.param_names_long, 'stdA');
M_.param_names = char(M_.param_names, 'stdG');
M_.param_names_tex = char(M_.param_names_tex, 'stdG');
M_.param_names_long = char(M_.param_names_long, 'stdG');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 12;
M_.endo_nbr = 137;
M_.param_nbr = 25;
M_.orig_endo_nbr = 109;
M_.aux_vars(1).endo_index = 110;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 45;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 111;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 46;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(3).endo_index = 112;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 46;
M_.aux_vars(3).orig_lead_lag = -2;
M_.aux_vars(4).endo_index = 113;
M_.aux_vars(4).type = 1;
M_.aux_vars(4).orig_index = 47;
M_.aux_vars(4).orig_lead_lag = -1;
M_.aux_vars(5).endo_index = 114;
M_.aux_vars(5).type = 1;
M_.aux_vars(5).orig_index = 47;
M_.aux_vars(5).orig_lead_lag = -2;
M_.aux_vars(6).endo_index = 115;
M_.aux_vars(6).type = 1;
M_.aux_vars(6).orig_index = 47;
M_.aux_vars(6).orig_lead_lag = -3;
M_.aux_vars(7).endo_index = 116;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 48;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(8).endo_index = 117;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 48;
M_.aux_vars(8).orig_lead_lag = -2;
M_.aux_vars(9).endo_index = 118;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 48;
M_.aux_vars(9).orig_lead_lag = -3;
M_.aux_vars(10).endo_index = 119;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 48;
M_.aux_vars(10).orig_lead_lag = -4;
M_.aux_vars(11).endo_index = 120;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 49;
M_.aux_vars(11).orig_lead_lag = -1;
M_.aux_vars(12).endo_index = 121;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 49;
M_.aux_vars(12).orig_lead_lag = -2;
M_.aux_vars(13).endo_index = 122;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 49;
M_.aux_vars(13).orig_lead_lag = -3;
M_.aux_vars(14).endo_index = 123;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 49;
M_.aux_vars(14).orig_lead_lag = -4;
M_.aux_vars(15).endo_index = 124;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 49;
M_.aux_vars(15).orig_lead_lag = -5;
M_.aux_vars(16).endo_index = 125;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 50;
M_.aux_vars(16).orig_lead_lag = -1;
M_.aux_vars(17).endo_index = 126;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 50;
M_.aux_vars(17).orig_lead_lag = -2;
M_.aux_vars(18).endo_index = 127;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 50;
M_.aux_vars(18).orig_lead_lag = -3;
M_.aux_vars(19).endo_index = 128;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 50;
M_.aux_vars(19).orig_lead_lag = -4;
M_.aux_vars(20).endo_index = 129;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 50;
M_.aux_vars(20).orig_lead_lag = -5;
M_.aux_vars(21).endo_index = 130;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 50;
M_.aux_vars(21).orig_lead_lag = -6;
M_.aux_vars(22).endo_index = 131;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 51;
M_.aux_vars(22).orig_lead_lag = -1;
M_.aux_vars(23).endo_index = 132;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 51;
M_.aux_vars(23).orig_lead_lag = -2;
M_.aux_vars(24).endo_index = 133;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 51;
M_.aux_vars(24).orig_lead_lag = -3;
M_.aux_vars(25).endo_index = 134;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 51;
M_.aux_vars(25).orig_lead_lag = -4;
M_.aux_vars(26).endo_index = 135;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 51;
M_.aux_vars(26).orig_lead_lag = -5;
M_.aux_vars(27).endo_index = 136;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 51;
M_.aux_vars(27).orig_lead_lag = -6;
M_.aux_vars(28).endo_index = 137;
M_.aux_vars(28).type = 1;
M_.aux_vars(28).orig_index = 51;
M_.aux_vars(28).orig_lead_lag = -7;
M_.Sigma_e = zeros(12, 12);
M_.Correlation_matrix = eye(12, 12);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('BGGsticky_static');
erase_compiled_function('BGGsticky_dynamic');
M_.orig_eq_nbr = 109;
M_.eq_nbr = 137;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 55 191;
 2 56 0;
 0 57 192;
 0 58 0;
 0 59 193;
 0 60 0;
 3 61 0;
 0 62 0;
 0 63 0;
 4 64 0;
 0 65 194;
 5 0 0;
 6 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 195;
 0 72 0;
 0 73 0;
 7 74 196;
 8 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 9 83 197;
 10 84 0;
 11 85 0;
 0 86 198;
 0 87 199;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 12 92 0;
 0 93 0;
 0 94 0;
 13 95 0;
 0 96 0;
 14 97 0;
 15 98 0;
 16 99 0;
 17 100 0;
 18 101 0;
 19 102 0;
 20 103 0;
 21 104 0;
 0 105 0;
 0 106 0;
 0 107 0;
 0 108 0;
 0 109 0;
 0 110 0;
 0 111 0;
 0 112 0;
 0 113 0;
 22 114 200;
 23 115 0;
 0 116 201;
 0 117 0;
 0 118 0;
 0 119 0;
 24 120 0;
 0 121 0;
 0 122 202;
 25 123 203;
 26 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 0;
 0 131 204;
 0 132 205;
 0 133 0;
 0 134 0;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 0 139 206;
 0 140 0;
 0 141 0;
 0 142 0;
 0 143 0;
 0 144 207;
 0 145 0;
 0 146 0;
 0 147 0;
 0 148 0;
 0 149 0;
 0 150 0;
 0 151 0;
 0 152 0;
 0 153 0;
 0 154 0;
 0 155 0;
 0 156 0;
 0 157 0;
 0 158 0;
 0 159 0;
 0 160 0;
 0 161 208;
 0 162 0;
 27 163 0;
 28 164 0;
 29 165 0;
 30 166 0;
 31 167 0;
 32 168 0;
 33 169 0;
 34 170 0;
 35 171 0;
 36 172 0;
 37 173 0;
 38 174 0;
 39 175 0;
 40 176 0;
 41 177 0;
 42 178 0;
 43 179 0;
 44 180 0;
 45 181 0;
 46 182 0;
 47 183 0;
 48 184 0;
 49 185 0;
 50 186 0;
 51 187 0;
 52 188 0;
 53 189 0;
 54 190 0;]';
M_.nstatic = 70;
M_.nfwrd   = 13;
M_.npred   = 49;
M_.nboth   = 5;
M_.nsfwrd   = 18;
M_.nspred   = 54;
M_.ndynamic   = 67;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:12];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(137, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(12, 1);
M_.params = NaN(25, 1);
M_.NNZDerivatives = [427; -1; -1];
M_.params( 7 ) = 0.0102;
ksie = M_.params( 7 );
M_.params( 1 ) = 0.33;
alphha = M_.params( 1 );
M_.params( 2 ) = 0.99;
betta = M_.params( 2 );
M_.params( 3 ) = 0.500;
gammma = M_.params( 3 );
M_.params( 6 ) = 0.025;
delta = M_.params( 6 );
M_.params( 4 ) = 5.584;
chil = M_.params( 4 );
M_.params( 5 ) = 0.333;
epsl = M_.params( 5 );
M_.params( 8 ) = 1.5;
eta = M_.params( 8 );
M_.params( 10 ) = 0.2;
G_over_Y = M_.params( 10 );
M_.params( 16 ) = 0.75;
gam = M_.params( 16 );
M_.params( 15 ) = 4.167;
els = M_.params( 15 );
M_.params( 17 ) = 1;
sig = M_.params( 17 );
M_.params( 13 ) = 1.5;
kpP = M_.params( 13 );
M_.params( 12 ) = 0.3;
kpY = M_.params( 12 );
M_.params( 19 ) = 7.0;
zzeta = M_.params( 19 );
M_.params( 18 ) = 1;
kap = M_.params( 18 );
M_.params( 14 ) = 0.7;
rho_r = M_.params( 14 );
M_.params( 20 ) = 0.97;
rhosigma = M_.params( 20 );
rhog     = 0.97;
M_.params( 21 ) = 0;
signal_corr_p = M_.params( 21 );
M_.params( 22 ) = 0.0282985;
stdsigma2_p = M_.params( 22 );
M_.params( 23 ) = 1;
stdsigma1_p = M_.params( 23 );
M_.params( 24 ) = 1;
stdA = M_.params( 24 );
M_.params( 25 ) = 1;
stdG = M_.params( 25 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (M_.params(24))^2;
M_.Sigma_e(2, 2) = (0)^2;
M_.Sigma_e(3, 3) = (M_.params(25))^2;
M_.Sigma_e(4, 4) = (0)^2;
M_.Sigma_e(5, 5) = (0)^2;
M_.Sigma_e(6, 6) = (0)^2;
M_.Sigma_e(7, 7) = (0)^2;
M_.Sigma_e(8, 8) = (0)^2;
M_.Sigma_e(9, 9) = (0)^2;
M_.Sigma_e(10, 10) = (0)^2;
M_.Sigma_e(11, 11) = (0)^2;
M_.Sigma_e(12, 12) = (1)^2;
steady;
resid(1); 
oo_.dr.eigval = check(M_,options_,oo_);
options_.nograph        = 1;
options_.irf = 40;
options_.order = 1;
options_.periods = 20000;
var_list_ = char();
info = stoch_simul(var_list_);
save('BGGsticky_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('BGGsticky_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('BGGsticky_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('BGGsticky_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('BGGsticky_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('BGGsticky_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('BGGsticky_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
