%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BGGflexi';
M_.dynare_version = '4.6.3';
oo_.dynare_version = '4.6.3';
options_.dynare_version = '4.6.3';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('BGGflexi.log');
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'e_A'};
M_.exo_names_tex(1) = {'e\_A'};
M_.exo_names_long(1) = {'e_A'};
M_.exo_names(2) = {'e_G'};
M_.exo_names_tex(2) = {'e\_G'};
M_.exo_names_long(2) = {'e_G'};
M_.exo_names(3) = {'e_KQ'};
M_.exo_names_tex(3) = {'e\_KQ'};
M_.exo_names_long(3) = {'e_KQ'};
M_.exo_names(4) = {'e_RS'};
M_.exo_names_tex(4) = {'e\_RS'};
M_.exo_names_long(4) = {'e_RS'};
M_.endo_names = cell(46,1);
M_.endo_names_tex = cell(46,1);
M_.endo_names_long = cell(46,1);
M_.endo_names(1) = {'C'};
M_.endo_names_tex(1) = {'C'};
M_.endo_names_long(1) = {'C'};
M_.endo_names(2) = {'Uc'};
M_.endo_names_tex(2) = {'Uc'};
M_.endo_names_long(2) = {'Uc'};
M_.endo_names(3) = {'Lambda'};
M_.endo_names_tex(3) = {'Lambda'};
M_.endo_names_long(3) = {'Lambda'};
M_.endo_names(4) = {'Lab'};
M_.endo_names_tex(4) = {'Lab'};
M_.endo_names_long(4) = {'Lab'};
M_.endo_names(5) = {'R'};
M_.endo_names_tex(5) = {'R'};
M_.endo_names_long(5) = {'R'};
M_.endo_names(6) = {'Y'};
M_.endo_names_tex(6) = {'Y'};
M_.endo_names_long(6) = {'Y'};
M_.endo_names(7) = {'K'};
M_.endo_names_tex(7) = {'K'};
M_.endo_names_long(7) = {'K'};
M_.endo_names(8) = {'W'};
M_.endo_names_tex(8) = {'W'};
M_.endo_names_long(8) = {'W'};
M_.endo_names(9) = {'Z'};
M_.endo_names_tex(9) = {'Z'};
M_.endo_names_long(9) = {'Z'};
M_.endo_names(10) = {'A'};
M_.endo_names_tex(10) = {'A'};
M_.endo_names_long(10) = {'A'};
M_.endo_names(11) = {'Rk'};
M_.endo_names_tex(11) = {'Rk'};
M_.endo_names_long(11) = {'Rk'};
M_.endo_names(12) = {'Rl'};
M_.endo_names_tex(12) = {'Rl'};
M_.endo_names_long(12) = {'Rl'};
M_.endo_names(13) = {'Ne'};
M_.endo_names_tex(13) = {'Ne'};
M_.endo_names_long(13) = {'Ne'};
M_.endo_names(14) = {'phie'};
M_.endo_names_tex(14) = {'phie'};
M_.endo_names_long(14) = {'phie'};
M_.endo_names(15) = {'Le'};
M_.endo_names_tex(15) = {'Le'};
M_.endo_names_long(15) = {'Le'};
M_.endo_names(16) = {'Ce'};
M_.endo_names_tex(16) = {'Ce'};
M_.endo_names_long(16) = {'Ce'};
M_.endo_names(17) = {'rho'};
M_.endo_names_tex(17) = {'rho'};
M_.endo_names_long(17) = {'rho'};
M_.endo_names(18) = {'rhoRex'};
M_.endo_names_tex(18) = {'rhoRex'};
M_.endo_names_long(18) = {'rhoRex'};
M_.endo_names(19) = {'omega'};
M_.endo_names_tex(19) = {'omega'};
M_.endo_names_long(19) = {'omega'};
M_.endo_names(20) = {'I'};
M_.endo_names_tex(20) = {'I'};
M_.endo_names_long(20) = {'I'};
M_.endo_names(21) = {'Q'};
M_.endo_names_tex(21) = {'Q'};
M_.endo_names_long(21) = {'Q'};
M_.endo_names(22) = {'psi'};
M_.endo_names_tex(22) = {'psi'};
M_.endo_names_long(22) = {'psi'};
M_.endo_names(23) = {'G'};
M_.endo_names_tex(23) = {'G'};
M_.endo_names_long(23) = {'G'};
M_.endo_names(24) = {'T'};
M_.endo_names_tex(24) = {'T'};
M_.endo_names_long(24) = {'T'};
M_.endo_names(25) = {'spread'};
M_.endo_names_tex(25) = {'spread'};
M_.endo_names_long(25) = {'spread'};
M_.endo_names(26) = {'sigmae'};
M_.endo_names_tex(26) = {'sigmae'};
M_.endo_names_long(26) = {'sigmae'};
M_.endo_names(27) = {'sigma_omega'};
M_.endo_names_tex(27) = {'sigma\_omega'};
M_.endo_names_long(27) = {'sigma_omega'};
M_.endo_names(28) = {'sigma_omega_ss'};
M_.endo_names_tex(28) = {'sigma\_omega\_ss'};
M_.endo_names_long(28) = {'sigma_omega_ss'};
M_.endo_names(29) = {'mon'};
M_.endo_names_tex(29) = {'mon'};
M_.endo_names_long(29) = {'mon'};
M_.endo_names(30) = {'bankrupt'};
M_.endo_names_tex(30) = {'bankrupt'};
M_.endo_names_long(30) = {'bankrupt'};
M_.endo_names(31) = {'Sg'};
M_.endo_names_tex(31) = {'Sg'};
M_.endo_names_long(31) = {'Sg'};
M_.endo_names(32) = {'YY'};
M_.endo_names_tex(32) = {'YY'};
M_.endo_names_long(32) = {'YY'};
M_.endo_names(33) = {'CC'};
M_.endo_names_tex(33) = {'CC'};
M_.endo_names_long(33) = {'CC'};
M_.endo_names(34) = {'II'};
M_.endo_names_tex(34) = {'II'};
M_.endo_names_long(34) = {'II'};
M_.endo_names(35) = {'WW'};
M_.endo_names_tex(35) = {'WW'};
M_.endo_names_long(35) = {'WW'};
M_.endo_names(36) = {'RR'};
M_.endo_names_tex(36) = {'RR'};
M_.endo_names_long(36) = {'RR'};
M_.endo_names(37) = {'QQ'};
M_.endo_names_tex(37) = {'QQ'};
M_.endo_names_long(37) = {'QQ'};
M_.endo_names(38) = {'RkRk'};
M_.endo_names_tex(38) = {'RkRk'};
M_.endo_names_long(38) = {'RkRk'};
M_.endo_names(39) = {'NeNe'};
M_.endo_names_tex(39) = {'NeNe'};
M_.endo_names_long(39) = {'NeNe'};
M_.endo_names(40) = {'spreadspread'};
M_.endo_names_tex(40) = {'spreadspread'};
M_.endo_names_long(40) = {'spreadspread'};
M_.endo_names(41) = {'KK'};
M_.endo_names_tex(41) = {'KK'};
M_.endo_names_long(41) = {'KK'};
M_.endo_names(42) = {'rhorho'};
M_.endo_names_tex(42) = {'rhorho'};
M_.endo_names_long(42) = {'rhorho'};
M_.endo_names(43) = {'LabLab'};
M_.endo_names_tex(43) = {'LabLab'};
M_.endo_names_long(43) = {'LabLab'};
M_.endo_names(44) = {'phiephie'};
M_.endo_names_tex(44) = {'phiephie'};
M_.endo_names_long(44) = {'phiephie'};
M_.endo_names(45) = {'psipsi'};
M_.endo_names_tex(45) = {'psipsi'};
M_.endo_names_long(45) = {'psipsi'};
M_.endo_names(46) = {'LeLe'};
M_.endo_names_tex(46) = {'LeLe'};
M_.endo_names_long(46) = {'LeLe'};
M_.endo_partitions = struct();
M_.param_names = cell(18,1);
M_.param_names_tex = cell(18,1);
M_.param_names_long = cell(18,1);
M_.param_names(1) = {'alphha'};
M_.param_names_tex(1) = {'alphha'};
M_.param_names_long(1) = {'alphha'};
M_.param_names(2) = {'betta'};
M_.param_names_tex(2) = {'betta'};
M_.param_names_long(2) = {'betta'};
M_.param_names(3) = {'gammma'};
M_.param_names_tex(3) = {'gammma'};
M_.param_names_long(3) = {'gammma'};
M_.param_names(4) = {'chil'};
M_.param_names_tex(4) = {'chil'};
M_.param_names_long(4) = {'chil'};
M_.param_names(5) = {'epsl'};
M_.param_names_tex(5) = {'epsl'};
M_.param_names_long(5) = {'epsl'};
M_.param_names(6) = {'delta'};
M_.param_names_tex(6) = {'delta'};
M_.param_names_long(6) = {'delta'};
M_.param_names(7) = {'ksie'};
M_.param_names_tex(7) = {'ksie'};
M_.param_names_long(7) = {'ksie'};
M_.param_names(8) = {'eta'};
M_.param_names_tex(8) = {'eta'};
M_.param_names_long(8) = {'eta'};
M_.param_names(9) = {'taf'};
M_.param_names_tex(9) = {'taf'};
M_.param_names_long(9) = {'taf'};
M_.param_names(10) = {'G_over_Y'};
M_.param_names_tex(10) = {'G\_over\_Y'};
M_.param_names_long(10) = {'G_over_Y'};
M_.param_names(11) = {'phiX'};
M_.param_names_tex(11) = {'phiX'};
M_.param_names_long(11) = {'phiX'};
M_.param_names(12) = {'kpY'};
M_.param_names_tex(12) = {'kpY'};
M_.param_names_long(12) = {'kpY'};
M_.param_names(13) = {'kpP'};
M_.param_names_tex(13) = {'kpP'};
M_.param_names_long(13) = {'kpP'};
M_.param_names(14) = {'els'};
M_.param_names_tex(14) = {'els'};
M_.param_names_long(14) = {'els'};
M_.param_names(15) = {'gam'};
M_.param_names_tex(15) = {'gam'};
M_.param_names_long(15) = {'gam'};
M_.param_names(16) = {'sig'};
M_.param_names_tex(16) = {'sig'};
M_.param_names_long(16) = {'sig'};
M_.param_names(17) = {'rhosigma'};
M_.param_names_tex(17) = {'rhosigma'};
M_.param_names_long(17) = {'rhosigma'};
M_.param_names(18) = {'rhog'};
M_.param_names_tex(18) = {'rhog'};
M_.param_names_long(18) = {'rhog'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 46;
M_.param_nbr = 18;
M_.orig_endo_nbr = 46;
M_.aux_vars = [];
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.orig_eq_nbr = 46;
M_.eq_nbr = 46;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 12 0;
 1 13 0;
 0 14 58;
 0 15 0;
 2 16 0;
 0 17 0;
 3 18 0;
 0 19 0;
 0 20 0;
 4 21 0;
 0 22 59;
 0 23 0;
 5 24 0;
 0 25 0;
 6 26 0;
 0 27 0;
 0 28 0;
 0 29 60;
 0 30 0;
 7 31 61;
 8 32 0;
 9 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 10 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 11 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 62;
 0 48 0;
 0 49 63;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;]';
M_.nstatic = 30;
M_.nfwrd   = 5;
M_.npred   = 10;
M_.nboth   = 1;
M_.nsfwrd   = 6;
M_.nspred   = 11;
M_.ndynamic   = 16;
M_.dynamic_tmp_nbr = [19; 14; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Uc' ;
  2 , 'name' , 'Lambda' ;
  3 , 'name' , '3' ;
  4 , 'name' , '4' ;
  5 , 'name' , 'Y' ;
  6 , 'name' , 'W' ;
  7 , 'name' , 'Z' ;
  8 , 'name' , 'K' ;
  9 , 'name' , 'Q' ;
  10 , 'name' , 'Rk' ;
  11 , 'name' , '11' ;
  12 , 'name' , 'Ne' ;
  13 , 'name' , 'Ce' ;
  14 , 'name' , '14' ;
  15 , 'name' , '15' ;
  16 , 'name' , 'omega' ;
  17 , 'name' , 'rho' ;
  18 , 'name' , 'rhoRex' ;
  19 , 'name' , '19' ;
  20 , 'name' , '20' ;
  21 , 'name' , 'G' ;
  22 , 'name' , '22' ;
  23 , 'name' , 'spread' ;
  24 , 'name' , '24' ;
  25 , 'name' , '25' ;
  26 , 'name' , '26' ;
  27 , 'name' , '27' ;
  28 , 'name' , 'bankrupt' ;
  29 , 'name' , 'YY' ;
  30 , 'name' , 'KK' ;
  31 , 'name' , 'II' ;
  32 , 'name' , 'CC' ;
  33 , 'name' , 'WW' ;
  34 , 'name' , 'LabLab' ;
  35 , 'name' , 'QQ' ;
  36 , 'name' , 'RR' ;
  37 , 'name' , 'RkRk' ;
  38 , 'name' , 'spreadspread' ;
  39 , 'name' , 'NeNe' ;
  40 , 'name' , 'rhorho' ;
  41 , 'name' , 'psipsi' ;
  42 , 'name' , 'phiephie' ;
  43 , 'name' , 'LeLe' ;
  44 , 'name' , 'sigmae' ;
  45 , 'name' , 'sigma_omega_ss' ;
  46 , 'name' , 'mon' ;
};
M_.mapping.C.eqidx = [1 20 32 ];
M_.mapping.Uc.eqidx = [1 2 4 ];
M_.mapping.Lambda.eqidx = [2 3 9 ];
M_.mapping.Lab.eqidx = [4 5 6 34 ];
M_.mapping.R.eqidx = [3 15 18 23 36 ];
M_.mapping.Y.eqidx = [4 5 6 7 20 22 29 ];
M_.mapping.K.eqidx = [5 7 8 11 12 13 14 15 16 20 30 ];
M_.mapping.W.eqidx = [6 33 ];
M_.mapping.Z.eqidx = [7 10 ];
M_.mapping.A.eqidx = [5 24 ];
M_.mapping.Rk.eqidx = [10 12 13 15 16 19 20 23 37 ];
M_.mapping.Rl.eqidx = [16 ];
M_.mapping.Ne.eqidx = [11 12 14 15 39 ];
M_.mapping.phie.eqidx = [14 42 ];
M_.mapping.Le.eqidx = [11 16 43 ];
M_.mapping.Ce.eqidx = [13 20 ];
M_.mapping.rho.eqidx = [17 18 40 ];
M_.mapping.rhoRex.eqidx = [18 19 ];
M_.mapping.omega.eqidx = [12 13 15 16 17 20 28 ];
M_.mapping.I.eqidx = [8 9 20 31 ];
M_.mapping.Q.eqidx = [9 10 11 12 13 14 16 20 35 ];
M_.mapping.psi.eqidx = [5 7 8 10 27 41 ];
M_.mapping.G.eqidx = [20 21 22 ];
M_.mapping.T.eqidx = [21 ];
M_.mapping.spread.eqidx = [23 ];
M_.mapping.sigmae.eqidx = [12 13 44 ];
M_.mapping.sigma_omega.eqidx = [12 13 15 17 20 26 28 45 ];
M_.mapping.sigma_omega_ss.eqidx = [26 45 ];
M_.mapping.mon.eqidx = [15 17 20 46 ];
M_.mapping.bankrupt.eqidx = [28 ];
M_.mapping.Sg.eqidx = [25 ];
M_.mapping.YY.eqidx = [29 ];
M_.mapping.CC.eqidx = [32 ];
M_.mapping.II.eqidx = [31 ];
M_.mapping.WW.eqidx = [33 ];
M_.mapping.RR.eqidx = [36 38 ];
M_.mapping.QQ.eqidx = [35 ];
M_.mapping.RkRk.eqidx = [37 38 ];
M_.mapping.NeNe.eqidx = [39 ];
M_.mapping.spreadspread.eqidx = [38 ];
M_.mapping.KK.eqidx = [30 ];
M_.mapping.rhorho.eqidx = [40 ];
M_.mapping.LabLab.eqidx = [34 ];
M_.mapping.phiephie.eqidx = [42 ];
M_.mapping.psipsi.eqidx = [41 ];
M_.mapping.LeLe.eqidx = [43 ];
M_.mapping.e_A.eqidx = [24 ];
M_.mapping.e_G.eqidx = [25 ];
M_.mapping.e_KQ.eqidx = [27 ];
M_.mapping.e_RS.eqidx = [26 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = true;
M_.state_var = [2 5 7 10 13 15 20 21 22 27 31 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(46, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(18, 1);
M_.endo_trends = struct('deflator', cell(46, 1), 'log_deflator', cell(46, 1), 'growth_factor', cell(46, 1), 'log_growth_factor', cell(46, 1));
M_.NNZDerivatives = [148; -1; -1; ];
M_.static_tmp_nbr = [16; 14; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(7) = 0.0102;
ksie = M_.params(7);
M_.params(1) = 0.33;
alphha = M_.params(1);
M_.params(2) = 0.99;
betta = M_.params(2);
M_.params(3) = 0.500;
gammma = M_.params(3);
M_.params(6) = 0.025;
delta = M_.params(6);
M_.params(4) = 5.584;
chil = M_.params(4);
M_.params(5) = 0.333;
epsl = M_.params(5);
M_.params(8) = 1.5;
eta = M_.params(8);
M_.params(10) = 0.2;
G_over_Y = M_.params(10);
M_.params(17) = 0.97;
rhosigma = M_.params(17);
M_.params(18) = 0.97;
rhog = M_.params(18);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
M_.Sigma_e(3, 3) = (1)^2;
M_.Sigma_e(4, 4) = (1)^2;
steady;
resid(1); 
oo_.dr.eigval = check(M_,options_,oo_);
options_.nograph        = 1;
options_.irf = 40;
options_.order = 1;
options_.periods = 10000;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
save('BGGflexi_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('BGGflexi_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('BGGflexi_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('BGGflexi_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('BGGflexi_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('BGGflexi_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('BGGflexi_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
