function [ys_, params, info] = RBC_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(12)=params(12);
    ys_(4)=1.0/params(7);
    ys_(24)=(1-params(6))/(ys_(4)-1+params(8));
    ys_(25)=(1-params(6))*params(8)/(ys_(4)-1+params(8));
    ys_(26)=1-ys_(25)-params(2);
    ys_(7)=params(6)*(1-params(5))/(params(6)*(1-params(5))+ys_(26)*params(5));
    ys_(8)=ys_(12)*ys_(7)*ys_(24)^((1-params(6))/params(6));
    ys_(9)=ys_(24)*ys_(8);
    ys_(10)=ys_(25)*ys_(8);
    ys_(5)=ys_(26)*ys_(8);
    ys_(13)=params(2)*ys_(8);
    ys_(6)=params(6)*ys_(8)/ys_(7);
    ys_(11)=ys_(13)/(ys_(7)*ys_(6));
    ys_(1)=1/(1-params(9))*(ys_(5)^((1-params(5))*(1-params(9)))*(1-ys_(7))^(params(5)*(1-params(9)))-1);
    ys_(2)=(1-ys_(7))^(params(5)*(1-params(9)))*(1-params(5))*ys_(5)^((1-params(5))*(1-params(9))-1);
    ys_(3)=ys_(5)^((1-params(5))*(1-params(9)))*(-params(5))*(1-ys_(7))^(params(5)*(1-params(9))-1);
    ys_(28)=params(7);
    ys_(15)=1;
    ys_(14)=1;
    ys_(16)=ys_(15)*2*params(14)*(ys_(14)-1)*ys_(14)^2/ys_(4);
    ys_(27)=ys_(4);
    ys_(18)=1;
    ys_(19)=1;
    ys_(20)=1;
    ys_(21)=1;
    ys_(22)=1;
    ys_(23)=1;
    ys_(17)=1;
    % Auxiliary equations
    check_=0;
end
